services:
  - type: web
    name: healara-monolithic
    env: node
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
