import React, { useState, useEffect, useContext } from 'react';
import api from '../api';
import { AuthContext } from '../context/AuthContext';
import { User, Settings as SettingsIcon, Save, Loader2 } from 'lucide-react';
import toast from 'react-hot-toast';

export default function Settings() {
  const { user, token } = useContext(AuthContext);
  
  // Dietary options list
  const DIETARY_OPTIONS = [
    'Vegetarian',
    'Vegan',
    'No dairy',
    'No gluten',
    'No nuts',
    'Halal',
    'Jain',
    'Low sodium',
    'Diabetic-friendly'
  ];

  const [selectedPreferences, setSelectedPreferences] = useState([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  // Fetch current user details on load to populate state
  useEffect(() => {
    const fetchUserProfile = async () => {
      try {
        setLoading(true);
        const res = await api.get('/auth/me');
        if (res.data.success && res.data.user) {
          setSelectedPreferences(res.data.user.dietaryPreferences || []);
        }
      } catch (err) {
        console.error('Error fetching user profile:', err);
        toast.error('Failed to load user settings.');
      } finally {
        setLoading(false);
      }
    };

    fetchUserProfile();
  }, []);

  // Toggle option selection state
  const handleTogglePreference = (option) => {
    const lowerOption = option.toLowerCase();
    if (selectedPreferences.includes(lowerOption)) {
      setSelectedPreferences(selectedPreferences.filter(p => p !== lowerOption));
    } else {
      setSelectedPreferences([...selectedPreferences, lowerOption]);
    }
  };

  // Submit/Save preferences to the API
  const handleSavePreferences = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      const res = await api.patch('/users/me/preferences', {
        dietaryPreferences: selectedPreferences
      });
      if (res.data.success) {
        toast.success('Dietary preferences updated successfully.');
      }
    } catch (err) {
      console.error('Error saving dietary preferences:', err);
      toast.error(err.response?.data?.message || 'Failed to save preferences.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="space-y-8 max-w-4xl w-full mx-auto py-6">
      {/* Title Header */}
      <div className="pb-2">
        <h1 className="text-[32px] font-bold text-gray-900 flex items-center gap-3 tracking-tight leading-none">
          <SettingsIcon className="h-9 w-9 text-teal-600" /> Account Settings
        </h1>
        <p className="text-[15px] text-gray-500 mt-2 font-medium">Configure your personal profile options and nutrition parameters</p>
      </div>

      {loading ? (
        <div className="p-12 text-center flex flex-col items-center justify-center gap-3 bg-white/90 backdrop-blur-sm border border-gray-100 rounded-xl min-h-[300px]">
          <Loader2 className="h-8 w-8 text-teal-600 animate-spin" />
          <span className="text-[13px] text-gray-400 font-bold uppercase tracking-wider">Loading settings...</span>
        </div>
      ) : (
        <form onSubmit={handleSavePreferences} className="bg-white rounded-2xl p-8 space-y-8 border border-gray-200 shadow-sm">
          
          {/* User Meta Summary */}
          <div className="flex items-center gap-5 pb-6 border-b border-gray-100">
            <div className="h-14 w-14 rounded-xl bg-teal-50 text-teal-700 font-bold text-[18px] border border-teal-100 flex items-center justify-center shadow-sm shrink-0">
              {user?.name?.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2)}
            </div>
            <div>
              <span className="font-bold text-[18px] text-gray-900 block tracking-tight leading-tight">{user?.name}</span>
              <span className="text-[14px] text-gray-500 block mt-1 font-medium">{user?.email} (Role: <span className="capitalize">{user?.role}</span>)</span>
            </div>
          </div>

          {/* Dietary Preferences Section */}
          <div className="space-y-4">
            <div>
              <h3 className="font-bold text-[18px] text-gray-800 flex items-center gap-2">
                <User className="h-5 w-5 text-teal-600" /> Dietary Preferences
              </h3>
              <p className="text-[14px] text-gray-500 mt-1 font-medium">Toggle preferences to customize nutritional guidelines generated by Claude.</p>
            </div>

            {/* Toggle Grid */}
            <div className="flex flex-wrap gap-3 pt-2">
              {DIETARY_OPTIONS.map(opt => {
                const lower = opt.toLowerCase();
                const isSelected = selectedPreferences.includes(lower);
                return (
                  <button
                    key={opt}
                    type="button"
                    onClick={() => handleTogglePreference(opt)}
                    className={`px-5 py-3 rounded-xl text-[14px] font-bold transition-premium border ${
                      isSelected
                        ? 'bg-teal-600 border-teal-600 text-white shadow-[0_2px_8px_rgba(13,148,136,0.25)]'
                        : 'bg-white border-gray-200 text-gray-700 hover:bg-gray-50'
                    }`}
                  >
                    {opt}
                  </button>
                );
              })}
            </div>

            {/* Hint Note */}
            <div className="pt-2 text-[12px] text-gray-400 font-medium italic">
              * Note: Your AI health coach uses these preferences to personalise your nutrition recommendations.
            </div>
          </div>

          {/* Save Action */}
          <div className="pt-6 border-t border-gray-100 flex justify-end">
            <button
              type="submit"
              disabled={saving}
              className="btn-primary"
            >
              {saving ? <Loader2 className="h-5 w-5 animate-spin" /> : <Save className="h-5 w-5" />}
              Save Preferences
            </button>
          </div>

        </form>
      )}

    </div>
  );
}
