import React, { useState, useEffect, useContext } from 'react';
import api from '../api';
import { AuthContext } from '../context/AuthContext';
import { User, Settings as SettingsIcon, Save, Loader2 } from 'lucide-react';
import toast from 'react-hot-toast';

export default function Settings() {
  const { user, token } = useContext(AuthContext);
  
  // Dietary options list
  const DIETARY_OPTIONS = [
    'Vegetarian',
    'Vegan',
    'No dairy',
    'No gluten',
    'No nuts',
    'Halal',
    'Jain',
    'Low sodium',
    'Diabetic-friendly'
  ];

  const [selectedPreferences, setSelectedPreferences] = useState([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  // Fetch current user details on load to populate state
  useEffect(() => {
    const fetchUserProfile = async () => {
      try {
        setLoading(true);
        const res = await api.get('/auth/me');
        if (res.data.success && res.data.user) {
          setSelectedPreferences(res.data.user.dietaryPreferences || []);
        }
      } catch (err) {
        console.error('Error fetching user profile:', err);
        toast.error('Failed to load user settings.');
      } finally {
        setLoading(false);
      }
    };

    fetchUserProfile();
  }, []);

  // Toggle option selection state
  const handleTogglePreference = (option) => {
    const lowerOption = option.toLowerCase();
    if (selectedPreferences.includes(lowerOption)) {
      setSelectedPreferences(selectedPreferences.filter(p => p !== lowerOption));
    } else {
      setSelectedPreferences([...selectedPreferences, lowerOption]);
    }
  };

  // Submit/Save preferences to the API
  const handleSavePreferences = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      const res = await api.patch('/users/me/preferences', {
        dietaryPreferences: selectedPreferences
      });
      if (res.data.success) {
        toast.success('Dietary preferences updated successfully.');
      }
    } catch (err) {
      console.error('Error saving dietary preferences:', err);
      toast.error(err.response?.data?.message || 'Failed to save preferences.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="space-y-6 max-w-2xl">
      {/* Title Header */}
      <div>
        <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
          <SettingsIcon className="h-7 w-7 text-teal-600" /> Account Settings
        </h1>
        <p className="text-xs text-gray-500 mt-1">Configure your personal profile options and nutrition parameters</p>
      </div>

      {loading ? (
        <div className="p-12 text-center flex flex-col items-center gap-2">
          <Loader2 className="h-8 w-8 text-teal-600 animate-spin" />
          <span className="text-xs text-gray-400 font-bold uppercase tracking-wider">Loading settings...</span>
        </div>
      ) : (
        <form onSubmit={handleSavePreferences} className="bg-white border border-gray-100 rounded-xl p-6 shadow-sm space-y-6">
          
          {/* User Meta Summary */}
          <div className="flex items-center gap-3 pb-5 border-b border-gray-100">
            <div className="h-10 w-10 rounded-full bg-teal-50 text-teal-700 font-bold text-sm flex items-center justify-center">
              {user?.name?.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2)}
            </div>
            <div>
              <span className="font-bold text-sm text-gray-900 block">{user?.name}</span>
              <span className="text-xs text-gray-500 block">{user?.email} (Role: <span className="capitalize">{user?.role}</span>)</span>
            </div>
          </div>

          {/* Dietary Preferences Section */}
          <div className="space-y-3">
            <div>
              <h3 className="font-bold text-sm text-gray-800 flex items-center gap-1.5">
                <User className="h-4.5 w-4.5 text-teal-600" /> Dietary Preferences
              </h3>
              <p className="text-xs text-gray-400 mt-0.5">Toggle preferences to customize nutritional guidelines generated by Claude.</p>
            </div>

            {/* Toggle Grid */}
            <div className="flex flex-wrap gap-2.5 pt-2">
              {DIETARY_OPTIONS.map(opt => {
                const lower = opt.toLowerCase();
                const isSelected = selectedPreferences.includes(lower);
                return (
                  <button
                    key={opt}
                    type="button"
                    onClick={() => handleTogglePreference(opt)}
                    className={`px-4 py-2 rounded-lg text-xs font-bold transition-all border ${
                      isSelected
                        ? 'bg-teal-600 border-teal-600 text-white shadow-sm'
                        : 'bg-white border-gray-300 text-gray-600 hover:bg-gray-50'
                    }`}
                  >
                    {opt}
                  </button>
                );
              })}
            </div>

            {/* Hint Note */}
            <div className="pt-2 text-xs text-gray-400 italic">
              * Note: Your AI health coach uses these preferences to personalise your nutrition recommendations.
            </div>
          </div>

          {/* Save Action */}
          <div className="pt-4 border-t flex justify-end">
            <button
              type="submit"
              disabled={saving}
              className="inline-flex items-center gap-1.5 px-5 py-2.5 bg-teal-600 hover:bg-teal-700 text-white rounded-lg text-xs font-bold transition-colors shadow-sm disabled:opacity-50"
            >
              {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4.5 w-4.5" />}
              Save Preferences
            </button>
          </div>

        </form>
      )}

    </div>
  );
}
